import type { NextPage } from 'next'
import Head from 'next/head'

import PageLayout from '../components/PageLayout'
import HelloWorld from '../components/HelloWorld'
import MuiHelloWorld from '../components/MuiHelloWorld'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <HelloWorld />
        <MuiHelloWorld />
      </PageLayout>
    </>
  )
}

export default Home
